### ISSUE TITLE
Ship of Harkinian keeps stopping error after installation.

### ISSUE THREAD

**Issue by Overpello** [Waterdish/Shipwright-Android#12]
I am trying the installation without PC method. Shipwright Android goes blank after extracting the ROM. Then it goes to the applications menu on my phone while still open in the background. When I go back to Shipwright Android or close and reopen Shipwright Android I receive the error "Ship of Harkinian keeps stopping". I've tried deleting the oot.ort file and restarting the application to create another ort file.

My phone is the moto g(6) play. I am using Android 9. I'm not sure if my phone has OpenGL ES 3.0. If not, I don't know how to obtain OpenGL ES 3.0.

**Comment by Waterdish** [comment]
I Googled it and your phone has opengles 3. That's odd that it's crashing. Is it crashing after the screen that says "extraction complete"?

**Comment by Overpello** [comment]
Yes it crashes after saying extraction complete. My phone has been acting up lately and might need to be reformatted before I try again.

**Comment by Waterdish** [comment]
Someone else had an issue with android 9 also. I'll see if I can reproduce the issue by testing that version.

**Comment by Waterdish** [comment]
This may be fixed in the new update. Let me know.

**Comment by Waterdish** [comment]
Closing this for now. Let me know if the issue still exists.
