### ISSUE TITLE
Master Quest file not recieving MQ tag

### ISSUE THREAD

**Issue by Horonelius** [Waterdish/Shipwright-Android#14]
So I am having an issue with save files created with the master quest option not actually becoming master quest saves. Everything acts like a vanilla save, and dungeons are normal. I figured maybe something was wrong with the files used, But PC SoH has no problems creating a master quest with them. 

Have tried making OTRs several times with no difference in behavior. OTRs created by the PC version cause the Android version to immediately crash on startup.

**Comment by Waterdish** [comment]
Known issue in the ship of harkinian code right now. When the fix is ready, I'll merge it into the android version.

**Comment by Horonelius** [comment]
In the meantime, copying a fresh MQ save over from PC is an acceptable workaround.

**Comment by Waterdish** [comment]
This should be fixed. Let me know if not.
