### ISSUE TITLE
Mapping the C buttons

### ISSUE THREAD

**Issue by Spaziopath** [Waterdish/Shipwright-Android#15]
Apologies if I sound like a dumb dumb, but I'm really struggling to map C-buttons. I'm using Android 11 and running the 1.02 soh.apk on a Retroid Pocket 3 Plus. I don't have an option to map the C-buttons in the settings. Any ideas?

**Comment by Waterdish** [comment]
I believe the c buttons are the right stick in the mapping settings. I could be wrong. I can check later.

**Comment by Spaziopath** [comment]
The right stick is mapped as "the right stick" with no C-buttons. Free camera is off

**Comment by Waterdish** [comment]
I think the option is there, it's just cut off. I can only see the C buttons when I snap the window to the top.
![Screenshot_20231102-224913_Ship of Harkinian](https://github.com/Waterdish/Shipwright-Android/assets/24773224/d24e79ef-dfc5-47be-b066-06422bfced5b)
![Screenshot_20231102-224817_Ship of Harkinian](https://github.com/Waterdish/Shipwright-Android/assets/24773224/d9b7ff0d-86c9-4b49-a5e6-fad7ab3b530d)
The UI scaling is going to be an issue for a little while longer. You might have better luck with the smallui version of the app.

**Comment by Spaziopath** [comment]
Thank you, this fixed the issue. I will pass this on to other RP3 owners

**Comment by Waterdish** [comment]
Great. The small UI version was better?
