### ISSUE TITLE
SoH Multi-player

### ISSUE THREAD

**Issue by FinnFurry** [Waterdish/Shipwright-Android#19]
If I transfer over the otr files for soh multi-player will it work on the Android app?

**Comment by Waterdish** [comment]
Idk. Try it and let me know

**Comment by FinnFurry** [comment]
> Idk. Try it and let me know

Ok, ill let you know when I do.

**Comment by Waterdish** [comment]
Closing this for now. Multiplayer will be added eventually when that code gets merged into the main SOH repo.
