### ISSUE TITLE
Crashing on Android 13

### ISSUE THREAD

**Issue by the-loan-wolf** [Waterdish/Shipwright-Android#2]
Here are logs:

`*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
LineageOS Version: '20.0-20230606-NIGHTLY-X00TD'
Build fingerprint: 'asus/WW_X00TD/ASUS_X00T_2:8.1.0/OPM1/15.2016.1805.318-20180712:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2023-10-16 13:55:17.769314754+0530
Process uptime: 2s
Cmdline: com.dishii.soh
pid: 4016, tid: 4046, name: SDLThread  >>> com.dishii.soh <<<
uid: 10500
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000020
Cause: null pointer dereference
    x0  0000000000000002  x1  0000007caef4ce18  x2  0000000000000001  x3  0000000000000000
    x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  695f6e6f63692f73
    x8  158c93e30c7efb70  x9  158c93e30c7efb70  x10 0000007bd2744000  x11 0000000000000000
    x12 7865745f5f52544f  x13 63692f7365727574  x14 0000000000000040  x15 0000000000000000
    x16 ffffffffffffffff  x17 0000000000000001  x18 0000007b6792a000  x19 0000007c5ef31b60
    x20 0000007b6a5342e8  x21 0000007bd2744000  x22 0000007bd2743210  x23 0000007caef4ce10
    x24 0000007c5ef31b90  x25 0000007bd2744000  x26 0000007bd27438cc  x27 0000007bfef19310
    x28 0000000000000000  x29 0000007bd2743140
    lr  0000007b6a213010  sp  0000007bd27430c0  pc  0000007b6a21302c  pst 0000000060000000
backtrace:
      #00 pc 0000000000ffb02c  /data/app/~~TXWdvx64D6q5JFojLcE61w==/com.dishii.soh-PuwspR82PQh7TXWV0d6NTw==/base.apk!libsoh.so (LUS::Gui::LoadGuiTexture(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, ImVec4 const&)+256) (BuildId: ba9253c601a818e6b1ccfa4480c2904339402480)
      #01 pc 00000000007dede8  /data/app/~~TXWdvx64D6q5JFojLcE61w==/com.dishii.soh-PuwspR82PQh7TXWV0d6NTw==/base.apk!libsoh.so (SaveEditorWindow::InitElement()+164) (BuildId: ba9253c601a818e6b1ccfa4480c2904339402480)
      #02 pc 0000000001004c8c  /data/app/~~TXWdvx64D6q5JFojLcE61w==/com.dishii.soh-PuwspR82PQh7TXWV0d6NTw==/base.apk!libsoh.so (LUS::GuiElement::Init()+32) (BuildId: ba9253c601a818e6b1ccfa4480c2904339402480)
      #03 pc 0000000000ff8594  /data/app/~~TXWdvx64D6q5JFojLcE61w==/com.dishii.soh-PuwspR82PQh7TXWV0d6NTw==/base.apk!libsoh.so (LUS::Gui::AddGuiWindow(std::__ndk1::shared_ptr<LUS::GuiWindow>)+464) (BuildId: ba9253c601a818e6b1ccfa4480c2904339402480)
      #04 pc 000000000074349c  /data/app/~~TXWdvx64D6q5JFojLcE61w==/com.dishii.soh-PuwspR82PQh7TXWV0d6NTw==/base.apk!libsoh.so (SohGui::SetupGuiElements()+2664) (BuildId: ba9253c601a818e6b1ccfa4480c2904339402480)
      #05 pc 00000000006ca7e8  /data/app/~~TXWdvx64D6q5JFojLcE61w==/com.dishii.soh-PuwspR82PQh7TXWV0d6NTw==/base.apk!libsoh.so (InitOTR+2056) (BuildId: ba9253c601a818e6b1ccfa4480c2904339402480)
      #06 pc 0000000000c749e0  /data/app/~~TXWdvx64D6q5JFojLcE61w==/com.dishii.soh-PuwspR82PQh7TXWV0d6NTw==/base.apk!libsoh.so (SDL_main+24) (BuildId: ba9253c601a818e6b1ccfa4480c2904339402480)
      #07 pc 000000000010dfe0  /data/app/~~TXWdvx64D6q5JFojLcE61w==/com.dishii.soh-PuwspR82PQh7TXWV0d6NTw==/base.apk!libSDL2.so (Java_org_libsdl_app_SDLActivity_nativeRunMain+688) (BuildId: d83d2447681099cd9acb4f055168d7fdc2a3426b)
      #08 pc 000000000021a354  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: dbc5942375f9e9be2b1aa6e1f2bd9e34)
      #09 pc 0000000000209398  /apex/com.android.art/lib64/libart.so (nterp_helper+152) (BuildId: dbc5942375f9e9be2b1aa6e1f2bd9e34)
      #10 pc 00000000000909fc  /data/app/~~TXWdvx64D6q5JFojLcE61w==/com.dishii.soh-PuwspR82PQh7TXWV0d6NTw==/base.apk (org.libsdl.app.SDLMain.run+168)
      #11 pc 000000000017f020  /system/framework/arm64/boot.oat (java.lang.Thread.run+80) (BuildId: 92c3edca9b2db78441b99fc40084dcac0121a9dd)
      #12 pc 000000000021096c  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+556) (BuildId: dbc5942375f9e9be2b1aa6e1f2bd9e34)
      #13 pc 000000000027af68  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+184) (BuildId: dbc5942375f9e9be2b1aa6e1f2bd9e34)
      #14 pc 0000000000624cac  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+460) (BuildId: dbc5942375f9e9be2b1aa6e1f2bd9e34)
      #15 pc 000000000066de60  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1296) (BuildId: dbc5942375f9e9be2b1aa6e1f2bd9e34)
      #16 pc 00000000000c2ba0  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: 0b46da0e5dd02588a4bea339d0e81f76)
      #17 pc 0000000000054c50  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 0b46da0e5dd02588a4bea339d0e81f76)`

**Comment by the-loan-wolf** [comment]
Yes i downloaded latest SoH version 7.1.1 and made new oot.otr and used PAL 1.1 rom and it is working on my PC

**Comment by Waterdish** [comment]
Not the latest release, the version in the playtesting section of the Readme. Annoyingly, it only works with the playtesting version and not the latest release (7.1.1). Sorry about that

**Comment by the-loan-wolf** [comment]
Ok, thank you for reminding me, now i will close this issue
