### ISSUE TITLE
Controller Config cutoff

### ISSUE THREAD

**Issue by skilarmbabcock** [Waterdish/Shipwright-Android#21]
There was a similar issue opened up but that was do to screen size. There is an issue even on larger screens where the controller input is just cut off which prevents being able to map all controls. This is especially difficult once you enter settings like Right stick camera and you have to map it. I was lucky that I could map mine but there is more inputs beyond that like the C buttons
![Screenshot_20231109-224241](https://github.com/Waterdish/Shipwright-Android/assets/152455783/bf6e4da6-70b2-41aa-ad3a-9ef4983aded2)

**Comment by duranphysics** [comment]
Same issue.

**Comment by PHIN1222** [comment]
I ran into the same issue but you can arrow over with the dpad (when mapped) and input a key randomly which should scroll it across to let you then correctly map the remaining c buttons etc.

**Comment by duranphysics** [comment]
I couldn't do it that way, but found out you can rescale the SoH GUI, and that allowed me to see all the options!

**Comment by Waterdish** [comment]
You can now also scroll horizontally in that window. No resizing necessary.
