### ISSUE TITLE
Add option to open enhancements menu without controller

### ISSUE THREAD

**Issue by skilarmbabcock** [Waterdish/Shipwright-Android#22]
For controllers that don't automatically have mapping, opening the menu to be able to get to said mapping function would be impossible. Perhaps a swipe down function could be added to remedy this.

**Comment by altheawesomeguy** [comment]
I have an odd setup (Anbernic) that does not have the buttons for the show/hide menu shortcut. I have thus managed to accidentally lock the menu as hidden.

**Comment by KyleBelmont** [comment]
With the most recent release 1.1.3, this can probably be marked as completed / finished. Came here to just say thanks for the update <3

**Comment by Waterdish** [comment]
<3
