### ISSUE TITLE
A way to add custom build mods like Leveled?

### ISSUE THREAD

**Issue by Kionea** [Waterdish/Shipwright-Android#24]
Some mods like the Leveled Mod utilize custom builds of the ship. I don't know if this is possible but is there a way the files in data could utilize a custom build? Attempting to replace them simply errors out saying the soh.otr version doesn't match.

**Comment by Waterdish** [comment]
A custom build can't be loaded from files. Realistically the easiest way to achieve this is to just for the SOH team to merge enough android changes that with any future custom build, its trivial to compile the custom build for Android.
