### ISSUE TITLE
Feature Request: >100% gyro sensitivity

### ISSUE THREAD

**Issue by Horonelius** [Waterdish/Shipwright-Android#31]
Would be nice if it was possible to set gyro sensitivity to more than 100% for an OoT3D feel.

**Comment by Waterdish** [comment]
I could add this to my build, but it's probably better to just request it for the main SOH repo.

**Comment by Horonelius** [comment]
Appears to already be several requests in main repository.

**Comment by Waterdish** [comment]
Then I'll close this for now. Looks like the devs are aware of it.
