### ISSUE TITLE
Can't bind certain buttons

### ISSUE THREAD

**Issue by TheJoetube** [Waterdish/Shipwright-Android#41]
I can't bind the R, Plus or Minus button when using switch controllers for some reason. I have tried 3 separate wired ones. 
They work correctly on the Windows version of SoH.
They are all third party controllers.
What could be the cause for this?

**Comment by Waterdish** [comment]
The android version of SDL detects controllers differently. I think it's just an android limitation. There's not much I can do for now, sorry.

**Comment by TheJoetube** [comment]
> The android version of SDL detects controllers differently. I think it's just an android limitation. There's not much I can do for now, sorry.

Oh, alright then.
