### ISSUE TITLE
link born only in his house 

### ISSUE THREAD

**Issue by Mesla7780** [Waterdish/Shipwright-Android#42]
When it happened I went out and entered the game, I simply went back to the link's house in the forest and it's really annoying to keep going back to where you were. Is this a bug or some kind of active configuration? 

Edit: I already talked to Zelda and I'm going to the dodongos cavern

**Comment by Waterdish** [comment]
This is just how ocarina of time is. You always start at link's house unless you were in a dungeon when you saved.

**Comment by Mesla7780** [comment]
Ok thank you
