### ISSUE TITLE
Will you add touch controls on this one as well?🤩

### ISSUE THREAD

**Issue by HJMBgit84** [Waterdish/Shipwright-Android#55]
Will you add touch controls on this one as well as you did on 2 ship? Please do it if you can because it is really great to see this working on Android 🙏🏻.
Thanks a lot for your great work.

**Comment by Waterdish** [comment]
Has touch controls now

**Comment by HJMBgit84** [comment]
Thanks, I love it. It took me a while to figure out how to get the touch
screen controls working since it is not set by default but now I know how
to enable it. I really appreciate it is one of my favorite games ☺️
