### ISSUE TITLE
Hiding Touch Controls (Including Toggle Button)

### ISSUE THREAD

**Issue by Eavilaswayce** [Waterdish/Shipwright-Android#57]
Hi there, I can see that just yesterday you released touch controls, fantastic work by the way. However, I use a controller with my phone and was wondering if there's any way to hide the toggle button for the touch controls. I've Googled around and looked in the Settings and I can't seem to find anything.

Thanks

**Comment by Waterdish** [comment]
Tap the eye in the bottom right :)

**Comment by Eavilaswayce** [comment]
Thanks for your reply, but I was asking about hiding that button in the bottom right, or making it only show when tapping the screen etc, something like that?

**Comment by Waterdish** [comment]
Oops yeah sorry I misread that. Ill probably implement something like that soon. For now you can just use the previous version without touch controls.

**Comment by Eavilaswayce** [comment]
Cheers, will do. Just another daft question before I close this issue, when opening the app there's a message that says "Press - to open the enhancements menu", is there a way to disable that? (I'm using the original logo screen restoration)

**Comment by Waterdish** [comment]
Perhaps but not that I know of. That is in the pc version of ship of harkinian so that's why it's here too
