### ISSUE TITLE
The First-person view is broken - the camera goes through Link's head

### ISSUE THREAD

**Issue by RDK083** [Waterdish/Shipwright-Android#6]

**Comment by Waterdish** [comment]
Is there still an issue with the latest update (1.1.0)? Could you also provide a screenshot if so.

**Comment by RDK083** [comment]
Yes(also, before the update the reticle was broken, it works properly now). 
Sorry if I confused you. Is there any way to fix the clipping?

**Comment by Waterdish** [comment]
Yeah I'll fix it eventually. The line of code that fixes the clipping on desktop doesn't work on android so I'll just need to find a workaround.

**Comment by Waterdish** [comment]
Fixed in latest update
